update .github/workflows/pr.yaml file

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -98,7 +98,6 @@ jobs:
   lint:
     name: Lint tool-list
     needs: setup
-    if: ${{ needs.setup.outputs.repository-list != '' || needs.setup.outputs.tool-list != '' }}
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
@@ -135,7 +134,6 @@ jobs:
   flake8:
     name: Lint Python scripts
     needs: setup
-    if: ${{ needs.setup.outputs.repository-list != '' }}
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
@@ -167,7 +165,6 @@ jobs:
   lintr:
     name: Lint R scripts
     needs: setup
-    if: ${{ needs.setup.outputs.repository-list != '' }}
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
@@ -226,7 +223,6 @@ jobs:
   file_sizes:
     name: Check file sizes
     needs: setup
-    if: ${{ github.event_name == 'pull_request' && needs.setup.outputs.repository-list != '' }}
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
@@ -255,7 +251,6 @@ jobs:
   test:
     name: Test tools
     needs: setup
-    if: ${{ needs.setup.outputs.repository-list != '' }}
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
@@ -319,7 +314,6 @@ jobs:
   combine_outputs:
     name: Combine chunked test results
     needs: [setup, test]
-    if: ${{ always() && needs.setup.outputs.repository-list != '' }}
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -360,86 +354,86 @@ jobs:
         fi
 
   # deploy the tools to the toolsheds (first TTS for testing)
-  deploy:
-    name: Deploy
-    needs: [setup, lint, flake8, lintr, combine_outputs]
-    if: ${{ (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' ) && github.repository_owner == 'galaxyproject' }}
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        python-version: ['3.7']
-    steps:
-    - uses: actions/checkout@v3
-      with:
-        fetch-depth: 1
-    - uses: actions/setup-python@v4
-      with:
-        python-version: ${{ matrix.python-version }}
-    - name: Cache .cache/pip
-      uses: actions/cache@v3
-      id: cache-pip
-      with:
-        path: ~/.cache/pip
-        key: pip_cache_py_${{ matrix.python-version }}_gxy_${{ needs.setup.outputs.galaxy-head-sha }}
-    - name: Deploy on testtoolshed
-      uses: galaxyproject/planemo-ci-action@v1
-      with:
-        mode: deploy
-        repository-list: ${{ needs.setup.outputs.repository-list }}
-        shed-target: testtoolshed
-        shed-key: ${{ secrets.TTS_API_KEY }}
-      continue-on-error: true
-    - name: Deploy on toolshed
-      uses: galaxyproject/planemo-ci-action@v1
-      with:
-        mode: deploy
-        repository-list: ${{ needs.setup.outputs.repository-list }}
-        shed-target: toolshed
-        shed-key: ${{ secrets.TS_API_KEY }}
+  # deploy:
+  #   name: Deploy
+  #   needs: [setup, lint, flake8, lintr, combine_outputs]
+  #   if: ${{ (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' ) && github.repository_owner == 'galaxyproject' }}
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     matrix:
+  #       python-version: ['3.7']
+  #   steps:
+  #   - uses: actions/checkout@v3
+  #     with:
+  #       fetch-depth: 1
+  #   - uses: actions/setup-python@v4
+  #     with:
+  #       python-version: ${{ matrix.python-version }}
+  #   - name: Cache .cache/pip
+  #     uses: actions/cache@v3
+  #     id: cache-pip
+  #     with:
+  #       path: ~/.cache/pip
+  #       key: pip_cache_py_${{ matrix.python-version }}_gxy_${{ needs.setup.outputs.galaxy-head-sha }}
+  #   - name: Deploy on testtoolshed
+  #     uses: galaxyproject/planemo-ci-action@v1
+  #     with:
+  #       mode: deploy
+  #       repository-list: ${{ needs.setup.outputs.repository-list }}
+  #       shed-target: testtoolshed
+  #       shed-key: ${{ secrets.TTS_API_KEY }}
+  #     continue-on-error: true
+  #   - name: Deploy on toolshed
+  #     uses: galaxyproject/planemo-ci-action@v1
+  #     with:
+  #       mode: deploy
+  #       repository-list: ${{ needs.setup.outputs.repository-list }}
+  #       shed-target: toolshed
+  #       shed-key: ${{ secrets.TS_API_KEY }}
 
-  deploy-report:
-    name: Report deploy status
-    needs: [deploy]
-    if: ${{ always() && needs.deploy.result != 'success' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' ) && github.repository_owner == 'galaxyproject' }}
-    runs-on: ubuntu-latest
-    steps:
-    # report to the PR if deployment failed
-    - name: Get PR object
-      uses: 8BitJonny/gh-get-current-pr@2.2.0
-      id: getpr
-      with:
-        sha: ${{ github.event.after }}
-    - name: Create comment
-      uses: peter-evans/create-or-update-comment@v2
-      with:
-        token: ${{ secrets.PAT }}
-        issue-number: ${{ steps.getpr.outputs.number }}
-        body: |
-          Attention: deployment ${{ needs.deploy.result }}!
+  # deploy-report:
+  #   name: Report deploy status
+  #   needs: [deploy]
+  #   if: ${{ always() && needs.deploy.result != 'success' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' ) && github.repository_owner == 'galaxyproject' }}
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #   # report to the PR if deployment failed
+  #   - name: Get PR object
+  #     uses: 8BitJonny/gh-get-current-pr@2.2.0
+  #     id: getpr
+  #     with:
+  #       sha: ${{ github.event.after }}
+  #   - name: Create comment
+  #     uses: peter-evans/create-or-update-comment@v2
+  #     with:
+  #       token: ${{ secrets.PAT }}
+  #       issue-number: ${{ steps.getpr.outputs.number }}
+  #       body: |
+  #         Attention: deployment ${{ needs.deploy.result }}!
 
-          https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
+  #         https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
 
-  determine-success:
-    name: Check workflow success
-    needs: [setup, lint, flake8, lintr, file_sizes, combine_outputs]
-    if: ${{ always() && github.ref != 'refs/heads/master' && github.ref != 'refs/heads/main' }}
-    runs-on: ubuntu-latest
-    steps:
-    - name: Check tool lint status
-      if: ${{ needs.lint.result != 'success' && needs.flake8.result != 'skipped' }}
-      run: exit 1
-    - name: Indicate Python script lint status
-      if: ${{ needs.flake8.result != 'success' && needs.flake8.result != 'skipped' }}
-      run: exit 1
-    - name: Indicate R script lint status
-      if: ${{ needs.lintr.result != 'success' && needs.lintr.result != 'skipped' }}
-      run: exit 1
-    - name: Indicate file size check status
-      if: ${{ needs.file_sizes.result != 'success' && needs.file_sizes.result != 'skipped' }}
-      run: exit 1
-    - name: Check tool test status
-      if: ${{ needs.combine_outputs.result != 'success' && needs.combine_outputs.result != 'skipped' }}
-      run: exit 1
+  # determine-success:
+  #   name: Check workflow success
+  #   needs: [setup, lint, flake8, lintr, file_sizes, combine_outputs]
+  #   if: ${{ always() && github.ref != 'refs/heads/master' && github.ref != 'refs/heads/main' }}
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #   - name: Check tool lint status
+  #     if: ${{ needs.lint.result != 'success' && needs.flake8.result != 'skipped' }}
+  #     run: exit 1
+  #   - name: Indicate Python script lint status
+  #     if: ${{ needs.flake8.result != 'success' && needs.flake8.result != 'skipped' }}
+  #     run: exit 1
+  #   - name: Indicate R script lint status
+  #     if: ${{ needs.lintr.result != 'success' && needs.lintr.result != 'skipped' }}
+  #     run: exit 1
+  #   - name: Indicate file size check status
+  #     if: ${{ needs.file_sizes.result != 'success' && needs.file_sizes.result != 'skipped' }}
+  #     run: exit 1
+  #   - name: Check tool test status
+  #     if: ${{ needs.combine_outputs.result != 'success' && needs.combine_outputs.result != 'skipped' }}
+  #     run: exit 1
 
 
 #       name: Galaxy Tool Linting and Tests for push and PR
@@ -841,46 +835,46 @@ jobs:
 #             exit 1
 #         fi
 
-  # deploy the tools to the toolsheds (first TTS for testing)
-  # deploy:
-  #   name: Deploy
-  #   needs: [setup, lint, flake8, lintr, combine_outputs]
-  #   strategy:
-  #     matrix:
-  #       python-version: [3.7]
-  #   runs-on: ubuntu-latest
-  #   if: github.ref == 'refs/heads/master' && github.repository_owner == 'frogs'
-  #   steps:
-  #   - uses: actions/checkout@v2
-  #     with:
-  #       fetch-depth: 1
-  #   - uses: actions/setup-python@v1
-  #     with:
-  #       python-version: ${{ matrix.python-version }}
-  #   - uses: actions/download-artifact@v2
-  #     with:
-  #       name: Workflow artifacts
-  #       path: ../workflow_artifacts/
-  #   - name: Cache .cache/pip
-  #     uses: actions/cache@v2
-  #     id: cache-pip
-  #     with:
-  #       path: ~/.cache/pip
-  #       key: pip_cache_py_${{ matrix.python-version }}_gxy_${{ needs.setup.outputs.galaxy_head_sha }}
-  #   - name: Install Planemo
-  #     run: pip install planemo
-  #   - name: Deploy on testtoolshed
-  #     env:
-  #       SHED_KEY: ${{ secrets.TTS_API_KEY }}
-  #     run: |
-  #       while read -r DIR; do
-  #           planemo shed_update --shed_target testtoolshed --shed_key "${{ env.SHED_KEY }}" --force_repository_creation "$DIR" || exit 1;
-  #       done < ../workflow_artifacts/repository_list.txt
-  #     continue-on-error: true
-  #   - name: Deploy on toolshed
-  #     env:
-  #       SHED_KEY: ${{ secrets.TS_API_KEY }}
-  #     run: |
-  #       while read -r DIR; do
-  #           planemo shed_update --shed_target toolshed --shed_key "${{ env.SHED_KEY }}" --force_repository_creation "$DIR" || exit 1;
-  #       done < ../workflow_artifacts/repository_list.txt
+#   deploy the tools to the toolsheds (first TTS for testing)
+#   deploy:
+#     name: Deploy
+#     needs: [setup, lint, flake8, lintr, combine_outputs]
+#     strategy:
+#       matrix:
+#         python-version: [3.7]
+#     runs-on: ubuntu-latest
+#     if: github.ref == 'refs/heads/master' && github.repository_owner == 'frogs'
+#     steps:
+#     - uses: actions/checkout@v2
+#       with:
+#         fetch-depth: 1
+#     - uses: actions/setup-python@v1
+#       with:
+#         python-version: ${{ matrix.python-version }}
+#     - uses: actions/download-artifact@v2
+#       with:
+#         name: Workflow artifacts
+#         path: ../workflow_artifacts/
+#     - name: Cache .cache/pip
+#       uses: actions/cache@v2
+#       id: cache-pip
+#       with:
+#         path: ~/.cache/pip
+#         key: pip_cache_py_${{ matrix.python-version }}_gxy_${{ needs.setup.outputs.galaxy_head_sha }}
+#     - name: Install Planemo
+#       run: pip install planemo
+#     - name: Deploy on testtoolshed
+#       env:
+#         SHED_KEY: ${{ secrets.TTS_API_KEY }}
+#       run: |
+#         while read -r DIR; do
+#             planemo shed_update --shed_target testtoolshed --shed_key "${{ env.SHED_KEY }}" --force_repository_creation "$DIR" || exit 1;
+#         done < ../workflow_artifacts/repository_list.txt
+#       continue-on-error: true
+#     - name: Deploy on toolshed
+#       env:
+#         SHED_KEY: ${{ secrets.TS_API_KEY }}
+#       run: |
+#         while read -r DIR; do
+#             planemo shed_update --shed_target toolshed --shed_key "${{ env.SHED_KEY }}" --force_repository_creation "$DIR" || exit 1;
+#         done < ../workflow_artifacts/repository_list.txt
